# Generated by Django 6.1 on 2026-08-28 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('badge_class', models.CharField(default='bg-info text-dark', help_text='Classes Bootstrap du badge', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Article categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Ex: evenements, temoignages', max_length=60)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('author_name', models.CharField(max_length=120)),
                ('excerpt', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.articlecategory')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
