# Generated by Django 6.1 on 2026-08-28 00:54

import admissions.models
import admissions.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondocument',
            name='file',
            field=models.FileField(storage=admissions.storage.PrivateDocumentStorage(), upload_to=admissions.models.admission_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='civil_document',
            field=models.FileField(storage=admissions.storage.PrivateDocumentStorage(), upload_to=admissions.models.admission_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_photo',
            field=models.ImageField(storage=admissions.storage.PrivateDocumentStorage(), upload_to=admissions.models.admission_upload_path),
        ),
    ]
