"""
Django settings for edmah_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k#9_ho#_lmf82_wbfobnt%r=5qj$2)molys$c%u5j$ak*b&7+0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Bibliothèques tierces
    'rest_framework',
    
    # Applications EDMAH
    'accounts',
    'catalog',
    'admissions',
    'learning',
    'events',
    'content',
    'communications',
    'certificates',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edmah_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'edmah_project.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'apprenant_dashboard'
LOGOUT_REDIRECT_URL = 'index'

# Règles métier EDMAH (P0/P1)
QUIZ_PASS_THRESHOLD = 80
MAX_ID_PHOTO_SIZE = 2 * 1024 * 1024  # 2 Mo
MAX_DOCUMENT_SIZE = 5 * 1024 * 1024  # 5 Mo
ADMIN_NOTIFICATION_EMAIL = 'contact@edmah.com'
DEFAULT_FROM_EMAIL = 'noreply@edmah.com'


# Base de données
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Validation des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalisation (Traduction Multilingue)
LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', _('Français')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Fichiers statiques (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fichiers médias téléversés (dossiers, pièces justificatives)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Stockage privé des pièces d'inscription : jamais servi par MEDIA_URL,
# uniquement accessible via la vue protégée admissions.views.serve_document.
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'


# Email (console backend pour le dev)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ============================================
# Jazzmin — interface d'administration EDMAH
# ============================================
JAZZMIN_SETTINGS = {
    'site_title': 'EDMAH Admin',
    'site_header': 'EDMAH',
    'site_brand': 'EDMAH Admin',
    'site_logo': 'images/logo.png',
    'login_logo': 'images/logo.png',
    'site_logo_classes': 'img-circle',
    'site_icon': 'images/logo.png',
    'welcome_sign': "Bienvenue dans l'administration EDMAH",
    'copyright': 'EDMAH — École du Mariage Harmonieux',
    'search_model': ['admissions.Inscription'],
    'user_avatar': None,

    'topmenu_links': [
        {'name': 'Voir le site', 'url': '/', 'new_window': True},
    ],

    'show_sidebar': True,
    'navigation_expanded': False,
    'hide_models': [],
    'order_with_respect_to': [
        'admissions', 'communications', 'catalog', 'events', 'learning',
        'content', 'certificates', 'accounts', 'auth',
    ],

    'icons': {
        'auth': 'fas fa-user-shield',
        'auth.Group': 'fas fa-users-gear',
        'accounts': 'fas fa-users',
        'accounts.User': 'fas fa-user',
        'admissions': 'fas fa-file-signature',
        'admissions.Inscription': 'fas fa-file-signature',
        'admissions.AdmissionDocument': 'fas fa-paperclip',
        'catalog': 'fas fa-graduation-cap',
        'catalog.Category': 'fas fa-tags',
        'catalog.Formation': 'fas fa-graduation-cap',
        'catalog.FormationHighlight': 'fas fa-star',
        'catalog.Session': 'fas fa-calendar-check',
        'certificates': 'fas fa-certificate',
        'certificates.Certificate': 'fas fa-certificate',
        'communications': 'fas fa-envelope-open-text',
        'communications.ContactMessage': 'fas fa-envelope',
        'communications.NewsletterSubscriber': 'fas fa-paper-plane',
        'content': 'fas fa-newspaper',
        'content.Article': 'fas fa-newspaper',
        'content.ArticleCategory': 'fas fa-tags',
        'content.FAQ': 'fas fa-circle-question',
        'content.GalleryItem': 'fas fa-images',
        'events': 'fas fa-calendar-days',
        'events.Event': 'fas fa-calendar-days',
        'events.EventRegistration': 'fas fa-ticket',
        'learning': 'fas fa-book-open',
        'learning.Course': 'fas fa-book',
        'learning.Module': 'fas fa-layer-group',
        'learning.Resource': 'fas fa-file-pdf',
        'learning.Quiz': 'fas fa-circle-question',
        'learning.Question': 'fas fa-list-check',
        'learning.Choice': 'fas fa-check',
        'learning.Attempt': 'fas fa-clipboard-check',
        'learning.Progress': 'fas fa-chart-line',
        'learning.Note': 'fas fa-note-sticky',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',

    'related_modal_active': True,

    'custom_css': 'css/jazzmin-custom.css',
    'custom_js': None,
    'use_google_fonts_cdn': True,
    'show_ui_builder': False,

    'changeform_format': 'horizontal_tabs',
    'language_chooser': True,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': True,
    'body_small_text': False,
    'brand_small_text': False,
    'accent': 'accent-warning',
    'navbar': 'navbar-dark',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': True,
    'theme': 'default',
    'default_theme_mode': 'light',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

