# Generated by Django 6.1 on 2026-08-28 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identifiant utilisé dans l'URL d'inscription", max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('duration_label', models.CharField(help_text='Ex: 8 semaines', max_length=60)),
                ('sessions_label', models.CharField(blank=True, help_text='Ex: 16 sessions', max_length=60)),
                ('audience', models.CharField(blank=True, help_text='Ex: Couples fiancés', max_length=120)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('en-ligne', 'En ligne'), ('hybride', 'Hybride')], default='presentiel', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, help_text='FCFA', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FormationHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-check', help_text='Classe FontAwesome, ex: fa-check', max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='catalog.formation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_open', models.BooleanField(default=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.formation')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
