# Generated by Django 6.1 on 2026-08-28 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Formateurs autorisés à gérer les modules, ressources et quiz de ce cours.', limit_choices_to={'role': 'formateur'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
